pub(super) fn render_math_symbol(symbol: &str, out: &mut String) {
    let command = match symbol {
        "∑" => Some(r"\sum"),
        "∏" => Some(r"\prod"),
        "∫" => Some(r"\int"),
        "∞" => Some(r"\infty"),
        "→" => Some(r"\to"),
        "←" => Some(r"\leftarrow"),
        "↔" => Some(r"\leftrightarrow"),
        "⇒" => Some(r"\Rightarrow"),
        "⇐" => Some(r"\Leftarrow"),
        "⇔" => Some(r"\Leftrightarrow"),
        "≤" => Some(r"\le"),
        "≥" => Some(r"\ge"),
        "≠" => Some(r"\ne"),
        "≈" => Some(r"\approx"),
        "∈" => Some(r"\in"),
        "∉" => Some(r"\notin"),
        "⊂" => Some(r"\subset"),
        "⊆" => Some(r"\subseteq"),
        "∂" => Some(r"\partial"),
        "…" => Some(r"\dots"),
        "α" => Some(r"\alpha"),
        "β" => Some(r"\beta"),
        "γ" => Some(r"\gamma"),
        "δ" => Some(r"\delta"),
        "ε" => Some(r"\epsilon"),
        "ζ" => Some(r"\zeta"),
        "η" => Some(r"\eta"),
        "θ" => Some(r"\theta"),
        "ι" => Some(r"\iota"),
        "κ" => Some(r"\kappa"),
        "λ" => Some(r"\lambda"),
        "μ" => Some(r"\mu"),
        "ν" => Some(r"\nu"),
        "ξ" => Some(r"\xi"),
        "π" => Some(r"\pi"),
        "ρ" => Some(r"\rho"),
        "σ" => Some(r"\sigma"),
        "τ" => Some(r"\tau"),
        "φ" => Some(r"\phi"),
        "χ" => Some(r"\chi"),
        "ψ" => Some(r"\psi"),
        "ω" => Some(r"\omega"),
        "Γ" => Some(r"\Gamma"),
        "Δ" => Some(r"\Delta"),
        "Θ" => Some(r"\Theta"),
        "Λ" => Some(r"\Lambda"),
        "Ξ" => Some(r"\Xi"),
        "Π" => Some(r"\Pi"),
        "Σ" => Some(r"\Sigma"),
        "Φ" => Some(r"\Phi"),
        "Ψ" => Some(r"\Psi"),
        "Ω" => Some(r"\Omega"),
        "‖" => Some(r"\Vert "),
        "⌊" => Some(r"\lfloor "),
        "⌋" => Some(r"\rfloor"),
        "⌈" => Some(r"\lceil "),
        "⌉" => Some(r"\rceil"),
        _ => None,
    };

    if let Some(command) = command {
        out.push_str(command);
    } else {
        out.push_str(symbol);
    }
}
