[package]
name = "typlite"
description = "Converts a subset of typst to markdown."
categories = ["compilers"]
keywords = ["language", "typst"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "typlite"
path = "src/main.rs"
required-features = ["cli"]
test = false
doctest = false
bench = false
doc = false

[dependencies]
clap = { workspace = true, optional = true }
ecow.workspace = true
env_logger = { workspace = true, optional = true }
tinymist-project = { workspace = true, features = ["lsp"] }
tinymist-std.workspace = true
typst.workspace = true

[features]
default = ["no-content-hint", "cli"]
clap = ["dep:clap"]
# Note: this is the feature for typlite as a CLI, not for others.
# `fonts` is enabled in CLI mode.
cli = ["clap", "clap/wrap_help", "env_logger", "fonts", "system"]
no-content-hint = ["tinymist-project/no-content-hint"]
docx = []

system = ["tinymist-project/system"]
web = ["tinymist-project/web"]

# Embeds Typst's default fonts for
# - text (Linux Libertine),
# - math (New Computer Modern Math), and
# - code (Deja Vu Sans Mono)
# and additionally New Computer Modern for text
# into the binary.
fonts = ["tinymist-project/fonts"]

[lints]
workspace = true
