[package]
name = "typlite"
description = "Placeholder crate for the next typlite implementation."
categories = ["compilers"]
keywords = ["language", "typst"]
authors.workspace = true
version.workspace = true
license.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "typlite"
path = "src/main.rs"
required-features = ["cli"]
test = false
doctest = false
bench = false
doc = false

[dependencies]
ecow.workspace = true
tinymist-project = { workspace = true, features = ["lsp"] }
tinymist-std.workspace = true
typst.workspace = true
typst-html.workspace = true
typst-syntax.workspace = true

[dev-dependencies]
insta.workspace = true
tinymist-tests.workspace = true

[build-dependencies]
typst.workspace = true

[features]
default = ["no-content-hint", "cli"]
clap = []
cli = []
docx = []
no-content-hint = ["tinymist-project/no-content-hint"]
system = ["tinymist-project/system"]
web = ["tinymist-project/web"]
fonts = ["tinymist-project/fonts"]

[lints]
workspace = true
